"""competition management fields

Revision ID: cfe3e4f1d020
Revises: c785fdb1417a
Create Date: 2026-07-18 13:01:47.413125
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe3e4f1d020'
down_revision: Union[str, None] = 'c785fdb1417a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True))
        # server_default backfills existing rows so NOT NULL is satisfiable; it's
        # then dropped since the app sets visibility on every insert (model default).
        batch_op.add_column(
            sa.Column('visibility', sa.String(), nullable=False, server_default='private')
        )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('visibility', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('visibility')
        batch_op.drop_column('registration_closes_at')
        batch_op.drop_column('registration_opens_at')

    # ### end Alembic commands ###
