"""challenges and categories

Revision ID: da88ecc9390a
Revises: 85962193e7da
Create Date: 2026-07-18 20:22:44.366236
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da88ecc9390a'
down_revision: Union[str, None] = '85962193e7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_categories_competition_id_competitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('competition_id', 'name', name='uq_category_name_per_competition')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_competition_id'), ['competition_id'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('case_insensitive', sa.Boolean(), nullable=False),
    sa.Column('flag_hash', sa.String(), nullable=True),
    sa.Column('flag_salt', sa.String(), nullable=True),
    sa.Column('flag_regex', sa.String(), nullable=True),
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_challenges_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_challenges_competition_id_competitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_competition_id'), ['competition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_competition_id'))
        batch_op.drop_index(batch_op.f('ix_challenges_category_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_competition_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
