"""auth and competition

Revision ID: c785fdb1417a
Revises: 59ec99f6ad80
Create Date: 2026-07-17 23:40:41.458264
"""
from datetime import datetime, timezone
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

# Reference data: the three built-in system roles (§7.3). Sourced from
# auth/seed.py so the migration and the test-fixture seeder insert identical
# rows. See ADR-0004 for why roles are seeded data rather than an enum.
from auth.seed import SYSTEM_ROLE_SPECS


# revision identifiers, used by Alembic.
revision: str = 'c785fdb1417a'
down_revision: Union[str, None] = '59ec99f6ad80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participation_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions'))
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('role_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('competition_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_role_assignments_competition_id_competitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_assignments_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('user_id', 'competition_id', 'role_id', name='uq_role_assignment')
    )
    with op.batch_alter_table('role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_assignments_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_assignments_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # Seed the three built-in system roles (§7.3).
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("is_system", sa.Boolean),
        sa.column("scope", sa.String),
        sa.column("permissions", sa.JSON),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        roles_table,
        [
            {
                "id": str(uuid4()),
                "name": spec["name"],
                "description": spec["description"],
                "is_system": True,
                "scope": spec["scope"],
                "permissions": spec["permissions"],
                "created_at": now,
            }
            for spec in SYSTEM_ROLE_SPECS
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_role_assignments_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_assignments_competition_id'))

    op.drop_table('role_assignments')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_token_hash'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('competitions')
    # ### end Alembic commands ###
