"""attachments

Revision ID: e127a3ac9202
Revises: da88ecc9390a
Create Date: 2026-07-19 10:30:20.425219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e127a3ac9202'
down_revision: Union[str, None] = 'da88ecc9390a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_attachments_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_attachments_competition_id_competitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_object_key'), ['object_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_object_key'))
        batch_op.drop_index(batch_op.f('ix_attachments_competition_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_challenge_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
